# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d38391d300544b485ed4e925cb287030c5a7bcdc68b1f00d0f30b03de9a10456a5237ea080ba7f3075ff8084e09fb7ce0f4967b53d13f70f97be07f30fc3c12a

test:
  secret_key_base: 5a513554187ba43d214a64fc5e6f85099fe4ea6f772f72698696a6a79e063043a95e6cccf7ae6f6296b3f619049e7f734d586df066539aaf1658679b0596d44b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
